version: "3.3"
# Указываем раздел со связанными сервисами

services:
    willy-wonka-admin-frontend:
        container_name: frontend
        build: ./
        expose:
            - "3000"
        ports:
            - "3000:3000"
        restart: always
        environment:
            - NODE_ENV=production
            - NUXT_PUBLIC_API_URL=http://localhost:7999/api
